/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Admin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilshan Wimalasuriya
 */
public class AdminUpdate extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminRegister
     * @param name
     * @param username
     * @param tphone
     * @param mail
     */

    private String username1;
    private String name1;
    private String mail1;
    private String phonenum1;
    AdminsInternalFrame aif;
       public AdminUpdate() {
        initComponents();
    }
    public AdminUpdate(String name,String username,String mail, String tphone,AdminsInternalFrame aif) {
        initComponents();
        lname.setText(name);
        uname.setText(username);
        email.setText(mail);
        phone.setText(tphone);
        username1 = username;
        name1 = name;
        mail1 = mail;
        phonenum1 = tphone;
        this.aif = aif;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(594, 330));
        setMinimumSize(new java.awt.Dimension(594, 330));
        getContentPane().setLayout(null);

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(275, 116, 187, 28);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-mail");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(108, 122, 51, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(108, 155, 49, 22);

        lname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        getContentPane().add(lname);
        lname.setBounds(275, 43, 187, 28);

        phone.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phone.setText("947XXXXXXXX");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(275, 150, 187, 28);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Full Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(108, 46, 80, 22);

        register.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        register.setText("Update");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(266, 245, 89, 31);

        uname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        getContentPane().add(uname);
        uname.setBounds(275, 77, 187, 28);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(108, 83, 77, 22);

        resetbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton);
        resetbutton.setBounds(373, 245, 89, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/594.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(594, 330));
        jLabel1.setMinimumSize(new java.awt.Dimension(594, 330));
        jLabel1.setPreferredSize(new java.awt.Dimension(594, 330));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 300);

        setBounds(-5, -35, 594, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        phone.setText("947");
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost

    }//GEN-LAST:event_phoneFocusLost

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.setText("947");
    }//GEN-LAST:event_phoneMouseClicked

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed

    }//GEN-LAST:event_phoneKeyPressed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        
        
        
        String name = lname.getText();
        String unam = uname.getText();
        String emai = email.getText();
        String phon = phone.getText();

        int atchar = -2;
        int dot = -1;
        for(int x = 0; x< emai.length(); x++)
        {
            if(emai.charAt(x) == '@')
            {
                atchar = x;
            }
            else if (emai.charAt(x) == '.')
            {
                dot = x;
            }
        }

        boolean checkphone = false;

        for (int y=0; y<phon.length(); y++)
        {
            if(Character.isDigit(phon.charAt(y)))
            {
                checkphone = true;
            }
            else
            {
                checkphone = false;
                break;
            }
        }

        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Name");
        }
        else if(unam.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Username");
        }
        else if(emai.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter an E-mail");
        }
        else if(phon.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Phone number");
        }  
        else if ((dot<atchar) || (dot == -1) || (atchar == -2))
        {
            JOptionPane.showMessageDialog(null, "Entered Email is not an valid Email address");
        }
        else if((phon.length()!=11) || (phon.charAt(0) != '9') || (phon.charAt(1) != '4') || (phon.charAt(2) != '7') || (checkphone == false))
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone number. You must use 94700000000 Format");
        }
        else
        {
            int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Update The Selected User Details?");
            int checkusername = unam.compareTo(username1);
            int checkemail =emai.compareTo(mail1);
            boolean usernamechanges = true;
            boolean emailchanges = true;
            if(x==0)
            {
                boolean status = false;
                boolean find = true;
                boolean changes = false;
                Admin ad = new Admin(name,unam,emai,phon);
                if((checkemail ==0) &&(checkusername ==0) )
                {
                    try {
                      status = ad.UpdateAdmin();
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(status)
                    {
                        this.dispose();
                        aif.LoaddTable();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error! Admin Details Not Updated");
                        aif.LoaddTable();
                    }
                    changes = true;
                }
                if(checkusername!=0)
                {
                    try {
                        find = ad.FindAdminFromUsername();
                    } catch (SQLException ex) {
                        Logger.getLogger(CustomerUpdate.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(find)
                    {
                        JOptionPane.showMessageDialog(null, "Cannot Update Admim, username : "+unam+" is unavailabel, Please Enter a Different Username");
                        usernamechanges = false;
                    }
                    else
                    {
                        usernamechanges = true;
                    }
                }
                if(checkemail!=0)
                {
                    System.out.println("email");
                    try {
                        find = ad.FindAdminFromEmail();
                    } catch (SQLException ex) {
                        Logger.getLogger(CustomerUpdate.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(find)
                    {
                        JOptionPane.showMessageDialog(null, "Cannot Update Admin, email : "+emai+" is unavailabel, Please Enter a Different email");
                        emailchanges = false;
                    }
                    else
                    {
                        emailchanges = true;
                    }
                }
                if((usernamechanges==true)&&(emailchanges==true)&&(changes==false))
                {
                    try {
                      status = ad.UpdateAdmin(username1);
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(status)
                    {
                        this.dispose();
                        aif.LoaddTable();
                    }
                }    
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        lname.setText(name1);
        uname.setText(username1);
        email.setText(mail1);
        phone.setText(phonenum1);
    }//GEN-LAST:event_resetbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField phone;
    private javax.swing.JButton register;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
