/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import ClassFiles.Customer;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilshan Wimalasuriya
 */
public class CustomerChangePassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminRegister
     */
    String uname;
    public CustomerChangePassword(String username) {
        initComponents();
        uname = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        conpassword = new javax.swing.JPasswordField();
        resetbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(591, 221));
        setMinimumSize(new java.awt.Dimension(591, 221));
        setVerifyInputWhenFocusTarget(false);
        getContentPane().setLayout(null);

        register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register.setText("Change Password");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(121, 143, 187, 25);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(129, 34, 56, 17);

        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(password);
        password.setBounds(284, 37, 199, 23);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirm Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(129, 69, 112, 17);

        conpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(conpassword);
        conpassword.setBounds(284, 70, 199, 23);

        resetbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton);
        resetbutton.setBounds(314, 143, 169, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/591.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(591, 221));
        jLabel1.setMinimumSize(new java.awt.Dimension(591, 221));
        jLabel1.setPreferredSize(new java.awt.Dimension(591, 221));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 190);

        setBounds(-5, -35, 1129, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        String pass = String.valueOf(password.getPassword());
        String cpass = String.valueOf(conpassword.getPassword());
        int passcheck = pass.compareTo(cpass);
        

        if(pass.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a Password");
        }
        else if(cpass.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please confirm the Password");
        }
        else if(pass.length()<8)
        {
            JOptionPane.showMessageDialog(null, "Your Password must contain 8 or more charactors");
        }
        else if (passcheck !=0)
        {
            JOptionPane.showMessageDialog(null, "Entered Password and Confirm Password does not match");
        }    
        else
        {
            int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Change The Password?");
            if(x==0)
            {
                boolean status = false;
                Customer cm = new Customer();
                cm.setPassword(pass);
                cm.setUsername(uname);
                try {
                    status = cm.ChangeCustomerPassword();
                }
                catch (SQLException ex) {
                    Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(status)
                {
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error! Customer Password was not changed");
                }
            }
        }
    }//GEN-LAST:event_registerActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        password.setText("");
        conpassword.setText("");
    }//GEN-LAST:event_resetbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JButton resetbutton;
    // End of variables declaration//GEN-END:variables
}
