/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Booking;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import ClassFiles.DBConnect;
import ClassFiles.VehicleType;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Dilshan Wimalasuriya
 */
public class CustomerUpdateBooking extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerRentVehicles
     */
    int cid;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    CustomerBookingInternalFrame cbi;
    BookingInternalFrame bif; 
    int bid;
    String type;
    public CustomerUpdateBooking(int bid, int cid,String type,CustomerBookingInternalFrame cbi ) throws SQLException {
        initComponents();
        this.cid = cid;
        this.bid = bid;
        this.cbi = cbi;
        this.type = type;
        Date date = new Date();
        startDate.setMinSelectableDate(date);
        endDate.setMinSelectableDate(date);
        
        con = DBConnect.connect();
        
        try {
            
            String query="Select typeName from vehicletype ";
            PreparedStatement stmnt = con.prepareStatement(query);
            rs = stmnt.executeQuery();
            
        } catch (Exception e){
            
            System.out.println(e);
            
        }
        while(rs.next())
        {
            String a = rs.getString("typeName");
            typebox.addItem(a);
        }
        typebox.setSelectedItem(type);
        
        
    }
    
    public CustomerUpdateBooking(int bid, int cid,String type,BookingInternalFrame bif ) throws SQLException {
        initComponents();
        this.cid = cid;
        this.bid = bid;
        this.bif = bif;
        this.type = type;
        Date date = new Date();
        startDate.setMinSelectableDate(date);
        endDate.setMinSelectableDate(date);
        
        con = DBConnect.connect();
        
        try {
            
            String query="Select typeName from vehicletype ";
            PreparedStatement stmnt = con.prepareStatement(query);
            rs = stmnt.executeQuery();
            
        } catch (Exception e){
            
            System.out.println(e);
            
        }
        while(rs.next())
        {
            String a = rs.getString("typeName");
            typebox.addItem(a);
        }
        typebox.setSelectedItem(type);
        
        
    }
    
    public CustomerUpdateBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(537, 267));
        setMinimumSize(new java.awt.Dimension(537, 267));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Start Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 80, 17);

        startDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(startDate);
        startDate.setBounds(273, 40, 103, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("End Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 80, 56, 17);

        typebox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(typebox);
        typebox.setBounds(273, 119, 103, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 120, 79, 17);

        endDate.setDateFormatString("yyyy-MM-dd");
        endDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                endDateMouseEntered(evt);
            }
        });
        getContentPane().add(endDate);
        endDate.setBounds(273, 81, 103, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Update Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 160, 129, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/537.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(537, 267));
        jLabel4.setMinimumSize(new java.awt.Dimension(537, 267));
        jLabel4.setPreferredSize(new java.awt.Dimension(537, 267));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 540, 240);

        setBounds(-5, -35, 537, 267);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Updated The Selected Booking?");
       if(x==0)
       {    
        Date stDate = startDate.getDate();
        Date edDate = endDate.getDate();
        String type = (String) typebox.getSelectedItem();
        int typeindex = (int) typebox.getSelectedIndex();
        if(stDate==null)
        {
            JOptionPane.showMessageDialog(null, "Please Select a Start Date");
        }
        else if(edDate==null)
        {
            JOptionPane.showMessageDialog(null, "Please Select an End Date");
        }
        else if(typeindex==0)
        {
            JOptionPane.showMessageDialog(null, "Please Select a Vehicle Type");
        }
        else if(stDate.after(edDate))
        {
            JOptionPane.showMessageDialog(null, "Start Date Cannot be a date after End Date");
        }    
        else
        {
             VehicleType vt = new VehicleType();
             vt.setTypeName(type);
             try {
                 vt.FindVehicleType(type);
             } catch (SQLException ex) {
                 Logger.getLogger(CustomerRentVehicles.class.getName()).log(Level.SEVERE, null, ex);
             }
             int typeId = vt.getTypeID();
             double keym = vt.getKeymoney();
             double dailyc = vt.getDailycharge();
             if(bif==null)
             {    
                 CustomerRentUpdateVehicleConfirm crv = new CustomerRentUpdateVehicleConfirm(bid,0,typeId, cid, stDate, edDate,type,keym,dailyc,cbi);
                 crv.setVisible(true);
             }
             else if(cbi==null)
             {
                 CustomerRentUpdateVehicleConfirm crv = new CustomerRentUpdateVehicleConfirm(bid,0,typeId, cid, stDate, edDate,type,keym,dailyc,bif);
                 crv.setVisible(true);
             }    
          }
       }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void endDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateMouseClicked

    }//GEN-LAST:event_endDateMouseClicked

    private void endDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateMouseEntered

    }//GEN-LAST:event_endDateMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JComboBox typebox;
    // End of variables declaration//GEN-END:variables
}
