/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Booking;
import ClassFiles.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Vince Lance
 */
public class CustomerBookingInternalFrame extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String model2 = null;
    int row = -1;
    int cid;
    
    public CustomerBookingInternalFrame(int cid) {
        initComponents();
        this.cid = cid;
        con = DBConnect.connect();
        LoaddTable();
    }
    
    public CustomerBookingInternalFrame() {
        initComponents();
    }
    
    
    public void LoaddTable(){
    
        try {
            String sql = "select b.bid as Booking_ID,vt.typeName as Vehicle_Type,b.StartDate as Start_Date,b.endDate as End_Date,b.charge as Charge from booking b, vehicletype vt where b.customerId="+cid+" AND b.vehicleId="+0+" AND vt.vtId=b.vtId";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        subpane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1394, 599));
        setMinimumSize(new java.awt.Dimension(1394, 599));
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(65, 13, 614, 265);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Update Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(705, 53, 119, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton2.setText("Delete Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(705, 110, 117, 25);
        getContentPane().add(error);
        error.setBounds(756, 342, 626, 0);

        subpane.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout subpaneLayout = new javax.swing.GroupLayout(subpane);
        subpane.setLayout(subpaneLayout);
        subpaneLayout.setHorizontalGroup(
            subpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        subpaneLayout.setVerticalGroup(
            subpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        getContentPane().add(subpane);
        subpane.setBounds(65, 296, 679, 198);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/1394.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1394, 599));
        jLabel1.setMinimumSize(new java.awt.Dimension(1394, 599));
        jLabel1.setPreferredSize(new java.awt.Dimension(1394, 599));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 730);

        setBounds(-5, -35, 1275, 762);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        row = jTable1.getSelectedRow();  
        if(row != -1)
        {
            int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete The Selected Booking?");
            if(x ==0)
            {
                int bid = (int) jTable1.getValueAt(row, 0);
                Booking b2 = new Booking(bid);
                try {
                    b2.DeleteBooking();
                } catch (SQLException ex) {
                    Logger.getLogger(CustomerBookingInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                LoaddTable();
            }
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Please Select The Booking You Want To Delete From The Table First");     
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        row = jTable1.getSelectedRow();  
        if(row != -1)
        {
            try {
                int bid = (int) jTable1.getValueAt(row, 0);
                String type = jTable1.getValueAt(row, 1).toString();
                CustomerUpdateBooking cu = new CustomerUpdateBooking(bid,cid,type,this);
                subpane.removeAll();
                subpane.add(cu).setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerBookingInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
           JOptionPane.showMessageDialog(null, "Please Select The Booking You Want To Update From The Table First");     
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDesktopPane subpane;
    // End of variables declaration//GEN-END:variables
}
