/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Booking;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import ClassFiles.DBConnect;
import ClassFiles.VehicleType;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Dilshan Wimalasuriya
 */
public class CustomerRentVehicles extends javax.swing.JInternalFrame {

    /**
     * Creates new form CustomerRentVehicles
     */
    int cid;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public CustomerRentVehicles(int cid) throws SQLException {
        initComponents();
        this.cid = cid;
        
        Date date = new Date();
        startDate.setMinSelectableDate(date);
        endDate.setMinSelectableDate(date);
        
        con = DBConnect.connect();
        typebox.addItem("--Please Select--");
        
        try {
            
            String query="Select typeName from vehicletype ";
            PreparedStatement stmnt = con.prepareStatement(query);
            rs = stmnt.executeQuery();
            
        } catch (Exception e){
            
            System.out.println(e);
            
        }
        while(rs.next())
        {
            String a = rs.getString("typeName");
            typebox.addItem(a);
        }
        
        
    }
    
    public CustomerRentVehicles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        typebox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        endDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(510, 330));
        setMinimumSize(new java.awt.Dimension(510, 330));
        setPreferredSize(new java.awt.Dimension(510, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Start Date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 80, 64, 17);

        startDate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(startDate);
        startDate.setBounds(250, 80, 103, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("End Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 120, 56, 17);

        typebox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(typebox);
        typebox.setBounds(250, 160, 103, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 160, 79, 17);

        endDate.setDateFormatString("yyyy-MM-dd");
        endDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endDateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                endDateMouseEntered(evt);
            }
        });
        getContentPane().add(endDate);
        endDate.setBounds(250, 120, 103, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Add Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 230, 111, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/AAA.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(510, 330));
        jLabel4.setMinimumSize(new java.awt.Dimension(510, 330));
        jLabel4.setPreferredSize(new java.awt.Dimension(510, 330));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1320, 680);

        setBounds(-5, -35, 1318, 709);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Date stDate = startDate.getDate();
       Date edDate = endDate.getDate();
       String type = (String) typebox.getSelectedItem();
       int typeindex = (int) typebox.getSelectedIndex();
       if(stDate==null)
       {
           JOptionPane.showMessageDialog(null, "Please Select a Start Date");
       }
       else if(edDate==null)
       {
           JOptionPane.showMessageDialog(null, "Please Select an End Date");
       }
       else if(typeindex==0)
       {
           JOptionPane.showMessageDialog(null, "Please Select a Vehicle Type");
       }
       else if(stDate.after(edDate))
       {
           JOptionPane.showMessageDialog(null, "Start Date Cannot be a date after End Date");
       }    
       else
       {
            VehicleType vt = new VehicleType();
            vt.setTypeName(type);
            try {
                vt.FindVehicleType(type);
            } catch (SQLException ex) {
                Logger.getLogger(CustomerRentVehicles.class.getName()).log(Level.SEVERE, null, ex);
            }
            int typeId = vt.getTypeID();
            double keym = vt.getKeymoney();
            double dailyc = vt.getDailycharge();
            CustomerRentVehicleConfirm crv = new CustomerRentVehicleConfirm(0,typeId, cid, stDate, edDate,type,keym,dailyc);
            crv.setVisible(true);
       }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void endDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateMouseClicked

    }//GEN-LAST:event_endDateMouseClicked

    private void endDateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateMouseEntered

    }//GEN-LAST:event_endDateMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JComboBox typebox;
    // End of variables declaration//GEN-END:variables
}
