/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.Booking;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vince Lance
 */
public class RentInternalFrame extends javax.swing.JInternalFrame {

    int bid;
    BookingInternalFrame table;
    public RentInternalFrame() {
        initComponents();
    }
    public RentInternalFrame(int bid, BookingInternalFrame table) {
        initComponents();
        this.bid = bid;
        this.table= table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        regnumbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle Registration Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 150, 179, 17);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Rent Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 180, 113, 25);

        regnumbox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        regnumbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnumboxActionPerformed(evt);
            }
        });
        getContentPane().add(regnumbox);
        regnumbox.setBounds(420, 140, 155, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/776.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(796, 432));
        jLabel2.setMinimumSize(new java.awt.Dimension(796, 432));
        jLabel2.setPreferredSize(new java.awt.Dimension(796, 432));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 390);

        setBounds(-5, -35, 751, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void regnumboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnumboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regnumboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Rent The Selected Booking?");
        if(x==0)
        {    
            String regnum = regnumbox.getText();
            try {
                Booking bk = new Booking();
                bk.Rent(regnum,this.bid);
                table.LoaddTable();
            } catch (SQLException ex) {
                Logger.getLogger(RentInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField regnumbox;
    // End of variables declaration//GEN-END:variables
}
