/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ClassFiles.DBConnect;
import ClassFiles.Model;
import ClassFiles.VehicleType;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Vince Lance
 */
public class VehicleTypeInternalFrame extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String model2 = null;
    int row = -1;
    
    public VehicleTypeInternalFrame() {
        initComponents();
        con = DBConnect.connect();
        LoaddTable();
    }

    
    public void LoaddTable(){
    
        try {
            String sql = "select typeName as Type_Name,keymoney as Keymoney,dailycharge as Daily_Charge from vehicletype";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    public boolean checkDigit(String value){
        boolean x=false;
        int count=0;
        
        for(int i=0;i<value.length();i++){
            if (Character.isDigit(value.charAt(i))){
                x= true;
            }
            else if(value.charAt(i)=='.'){
                count++;
                if(count>1){
                    x=false;
                    break;
                }
                x=true;
            }
            else{
                x= false;
                break;
            }
        }
        
        return x;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        typenamebox = new javax.swing.JTextField();
        keymoneybox = new javax.swing.JTextField();
        dailychargebox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1134, 573));
        setMinimumSize(new java.awt.Dimension(1134, 573));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(94, 103, 116, 28);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Key Money");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(94, 169, 119, 28);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daily Charge");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(94, 238, 137, 28);

        typenamebox.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(typenamebox);
        typenamebox.setBounds(312, 110, 150, 22);

        keymoneybox.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(keymoneybox);
        keymoneybox.setBounds(312, 176, 150, 22);

        dailychargebox.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        getContentPane().add(dailychargebox);
        dailychargebox.setBounds(312, 245, 150, 22);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(566, 103, 452, 252);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Add Type");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(215, 423, 83, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton2.setText("Update Type");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(335, 423, 97, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton3.setText("Delete Type");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(464, 423, 97, 25);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton5.setText("Generate Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(599, 423, 123, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/1134.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1134, 573));
        jLabel4.setMinimumSize(new java.awt.Dimension(1134, 573));
        jLabel4.setPreferredSize(new java.awt.Dimension(1134, 573));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1250, 580);

        setBounds(-5, -35, 1215, 653);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String check = typenamebox.getText();
        int x = check.compareTo("");
        if (x==0){
            JOptionPane.showMessageDialog(null, "Cannot Perform Action: A typename should be entered");
        }
        else if(keymoneybox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter Key Money valeu");
        }
        else if(checkDigit(keymoneybox.getText())==false){
            JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Key Money value");
        }
        else if(dailychargebox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter the daily charge");
        }
        else if(checkDigit(dailychargebox.getText())==false){
            JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Daily Charge value");
        }
        else{
            String typename = typenamebox.getText().toUpperCase();
            double keymoney = Double.parseDouble(keymoneybox.getText());
            double dailycharge = Double.parseDouble(dailychargebox.getText());
            VehicleType vt = new VehicleType(typename,keymoney,dailycharge);
            try {
                vt.AddVehicleType();
                LoaddTable();
                typenamebox.setText("");
                keymoneybox.setText("");
                dailychargebox.setText("");
            }
            catch (SQLException ex) {
                Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = -1;
        row = jTable1.getSelectedRow();
        if(row !=-1)
        {
            String check = typenamebox.getText();
            int x = check.compareTo("");
            if (x==0){
                JOptionPane.showMessageDialog(null, "Cannot Perform Action: A typename should be entered");
            }
            else if(keymoneybox.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter Key Money valeu");
            }
            else if(checkDigit(keymoneybox.getText())==false){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Key Money value");
            }
            else if(dailychargebox.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter the daily charge");
            }
            else if(checkDigit(dailychargebox.getText())==false){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Daily Charge value");
            }
            else{

                row = jTable1.getSelectedRow();
                String prevtypename = jTable1.getValueAt(row, 0).toString();
                String typename = typenamebox.getText().toUpperCase();
                String inputtype = typename;
                int vehicletypecount = -1;
                double keymoney = Double.parseDouble(keymoneybox.getText());
                double dailycharge = Double.parseDouble(dailychargebox.getText());
                VehicleType vt = new VehicleType(typename,keymoney,dailycharge);
                int changes = prevtypename.compareTo(typename);
                if(changes==0)
                {
                    try {
                    vt.UpdateVehicleType();
                    LoaddTable();
                    typenamebox.setText("");
                    keymoneybox.setText("");
                    dailychargebox.setText("");
                    }
                    catch (SQLException ex) {
                        Logger.getLogger(AdminsInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else
                {
                    try {
                        vehicletypecount = vt.FindVehicleTypeCount();
                    } catch (SQLException ex) {
                        Logger.getLogger(VehicleTypeInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if(vehicletypecount==0)
                    {
                        try {
                            vt.UpdateVehicleType(prevtypename);
                            LoaddTable();
                            typenamebox.setText("");
                            keymoneybox.setText("");
                            dailychargebox.setText("");
                        } catch (SQLException ex) {
                            Logger.getLogger(VehicleTypeInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Vehicle Type not Updated. Type name : "+typename+" has been taken already");
                    }       
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Select a Vehicle Type to Update From the List");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        row = jTable1.getSelectedRow();
        String typename = jTable1.getValueAt(row, 0).toString();
        String inputtype = typename;
        String keymoney = jTable1.getValueAt(row, 1).toString();
        String dailycharge = jTable1.getValueAt(row, 2).toString();
        
        typenamebox.setText(typename);
        keymoneybox.setText(keymoney);
        dailychargebox.setText(dailycharge);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = -1;
        row = jTable1.getSelectedRow();
        if(row !=-1)
        {
            String check = typenamebox.getText();
            int x = check.compareTo("");
            if (x==0){
                JOptionPane.showMessageDialog(null, "Cannot Perform Action: A typename should be entered");
            }
            else if(keymoneybox.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter Key Money valeu");
            }
            else if(checkDigit(keymoneybox.getText())==false){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Key Money value");
            }
            else if(dailychargebox.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Please enter the daily charge");
            }
            else if(checkDigit(dailychargebox.getText())==false){
                JOptionPane.showMessageDialog(null, "Cannot Perform action : Invalid Daily Charge value");
            }
            else{
                String typename = typenamebox.getText().toUpperCase();
                double keymoney = Double.parseDouble(keymoneybox.getText());
                double dailycharge = Double.parseDouble(dailychargebox.getText());
                VehicleType vt = new VehicleType(typename,keymoney,dailycharge);
                vt.DeleteVehicleType();
                LoaddTable();
                typenamebox.setText("");
                keymoneybox.setText("");
                dailychargebox.setText("");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Select a Vehicle Type to Delete From the List");
        }    
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        // Compile jrxml file.
        JasperReport jasperReport;
        try {
            // Compile jrxml file.
            jasperReport = JasperCompileManager.compileReport("src/Reports/VehicleTypesReport.jrxml");

            // Parameters for report
            Map<String, Object> parameters = new HashMap<String, Object>();

            // DataSource
            Connection conn = DBConnect.connect();
            // This is simple example, no database.
            // then using empty datasource.

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,
                parameters,conn);

            // Make sure the output directory exists.
            File outDir = new File("src/jasperoutput");
            outDir.mkdirs();

            // Export to PDF.
            JasperExportManager.exportReportToPdfFile(jasperPrint,
                "src/jasperoutput/VehicleTypesReport.pdf");

            System.out.println("Done!");
        } catch (JRException ex) {
            Logger.getLogger(CustomersInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        File file = new File("src/jasperoutput/VehicleTypesReport.pdf");
        if(file.exists())
        {
            try {
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                Logger.getLogger(CustomersInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dailychargebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keymoneybox;
    private javax.swing.JTextField typenamebox;
    // End of variables declaration//GEN-END:variables
}
